version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/PFM-API
    environment:
    - MAVEN_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "~/PFM-API/spring-javaj2eefsd-workshop/pom.xml"
          }}
        - v1-dependencies-
    - run: mvn -f ~/PFM-API/spring-javaj2eefsd-workshop/pom.xml dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "~/PFM-API/spring-javaj2eefsd-workshop/pom.xml"
          }}
    - run: mvn -f ~/PFM-API/spring-javaj2eefsd-workshop/pom.xml clean install
  deploy:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/PFM-API
    environment:
    - MAVEN_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "~/PFM-API/spring-javaj2eefsd-workshop/pom.xml" }}
        - v1-dependencies-
    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "~/PFM-API/spring-javaj2eefsd-workshop/pom.xml"}}
    - run: git subtree --prefix spring-javaj2eefsd-workshop push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git public_access_offshore:master
workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build:
        filters:
          branches:
            only: public_access
    - deploy:
        requires:
        - build
        filters:
          branches:
            only: public_access